### ISSUE TITLE
Azure devops pipeline not working

### ISSUE THREAD

**Issue by nilakky** [Azure/gitops-connector#42]
Below are the steps to reproduce the issue:
1. Perform more than one commit within 1 minute (spec.interval for the flux customization)
2. Reconciliation happens with both the commits, and we can see the latest deployment
3. But only latest commit shows reconciliation status in azure repo against the commit but older one did not.
4. Also, only one CD pipeline completes successfully, and older commit pipeline fails after 60 minutes.

Issue seems to be with gitops connector which should send the notification to the respective commit when there are multiple commits within the interval.

**Comment by eedorenko** [comment]
I believe in this case the Flux reconciliation happens only for the latest commit. Flux just ignores the first commit therefore it doesn't notify the GitOps Connector on it.

With that said, this is expected behavior:
  - Commit status on the first commit is not updated because it has never been reconciled
  - CD pipeline on the first commit  is timed out because it doesn't make sense anymore
