### ISSUE TITLE
Not possible to use with GitHub for manifest repository when using Azure DevOps for CI/CD

### ISSUE THREAD

**Issue by jozala** [Azure/gitops-connector#43]
I was not able to configure the GitOps Connector to work with Azure DevOps as CI/CD and GitHub for Manifests repository.
As far as I understand this is currently not possible to use it like this. The tool can be used only if both Manifests repository and CI/CD pipelines are on one - either GitHub or Azure DevOps, but not mixed.
Could you please confirm that?

If that's the case, could this be clearly stated in the documentation? Currently, the configuration have separate fields for `gitRepositoryType` and `ciCdOrchestratorType` which imply they can be set to different values and work.

From what I understand, to use Azure DevOps pipeline agentless waiting for deployment status - we need to push information about the callback to Git pull request properties, but setting properties is only available in Azure DevOps repositories and not in GitHub. 
Could you suggest some workaround for this?

**Comment by eedorenko** [comment]
1. True. The reason why it's not possible is that you can provide only single PAT which is used for both orchestrator and repository. It's fairly easy to update that behavior so one can provide separate tokens. 
2. However, even with implementing No 1, it still won't work due to the reason you mentioned. GH doesn't have PR properties. The method [get_pr_metadata](https://github.com/Azure/gitops-connector/blob/6b36589c98beb53b564aa2b838d8d045f0d0794d/src/repositories/github_git_repository.py#LL99C10-L99C10) is not implemented for GH.

That's why there are two different ways of using GitOps Connector:
- With Azdo. Described [here](https://learn.microsoft.com/en-us/azure/azure-arc/kubernetes/tutorial-gitops-flux2-ci-cd#implement-cicd-with-azure-devops) and [here](https://github.com/Azure/arc-cicd-demo-src/blob/master/docs/azdo-gitops.md) 
- With GitHub. Described [here](https://learn.microsoft.com/en-us/azure/azure-arc/kubernetes/tutorial-gitops-flux2-ci-cd#implement-cicd-with-github) and [here](https://github.com/Azure/arc-cicd-demo-src/blob/master/docs/azdo-gitops-githubfluxv2.md) 

PRs are welcome.
